# Generated by Django 3.2.7 on 2022-01-22 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module_budget', '0002_auto_20220106_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
