# Generated by Django 3.2.7 on 2021-09-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0005_auto_20210920_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='customers_access',
            new_name='assets_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='deliveries_access',
            new_name='bills_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='kitchen_stock_access',
            new_name='bookings_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='menu_access',
            new_name='checkin_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='orders_access',
            new_name='guests_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='reservations_access',
            new_name='housekeeping_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='sittings_access',
            new_name='rooms_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='tables_access',
            new_name='services_access',
        ),
    ]
