# Generated by Django 3.2.7 on 2022-01-24 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task_item', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_date', models.DateField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_tasks.taskgroup', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
