# Generated by Django 3.2.7 on 2022-01-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
