# Generated by Django 3.2.7 on 2022-01-22 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module_notes', '0003_delete_notefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
