# Generated by Django 3.2.7 on 2021-09-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_account'),
        ('module_admin', '0004_auto_20210919_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', to_field='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', to_field='id'),
        ),
    ]
