# Generated by Django 3.2.7 on 2021-09-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0005_auto_20210920_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='deliveries_access',
            new_name='cashflow_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='kitchen_stock_access',
            new_name='inventory_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='menu_access',
            new_name='invoice_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='reservations_access',
            new_name='marketting_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='roster_access',
            new_name='payables_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='sittings_access',
            new_name='products_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='tables_access',
            new_name='purchasing_access',
        ),
        migrations.AddField(
            model_name='access',
            name='receivables_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='sales_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='suppliers_access',
            field=models.BooleanField(default=False),
        ),
    ]
