# Generated by Django 3.2.7 on 2021-09-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0005_auto_20210920_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='customers_access',
            new_name='contractors_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='deliveries_access',
            new_name='equipment_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='kitchen_stock_access',
            new_name='manufacturing_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='menu_access',
            new_name='materials_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='payments_access',
            new_name='projects_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='reservations_access',
            new_name='purchasing_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='sittings_access',
            new_name='stock_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='staff_access',
            new_name='tasks_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='tables_access',
            new_name='workers_access',
        ),
    ]
