# Generated by Django 3.2.7 on 2021-09-19 01:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_profile_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_level', models.CharField(max_length=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invitee_id', models.CharField(max_length=200, null=True)),
                ('invitee_name', models.CharField(max_length=200, null=True)),
                ('invitation_status', models.CharField(max_length=30, null=True)),
                ('date_sent', models.DateTimeField(auto_now=True, null=True)),
                ('date_confirmed', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_access', models.BooleanField(default=False)),
                ('portal_access', models.BooleanField(default=False)),
                ('settings_access', models.BooleanField(default=False)),
                ('menu_access', models.BooleanField(default=False)),
                ('staff_access', models.BooleanField(default=False)),
                ('tables_access', models.BooleanField(default=False)),
                ('customers_access', models.BooleanField(default=False)),
                ('deliveries_access', models.BooleanField(default=False)),
                ('payments_access', models.BooleanField(default=False)),
                ('roster_access', models.BooleanField(default=False)),
                ('reservations_access', models.BooleanField(default=False)),
                ('orders_access', models.BooleanField(default=False)),
                ('kitchen_stock_access', models.BooleanField(default=False)),
                ('sittings_access', models.BooleanField(default=False)),
                ('id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='module_admin.user', to_field='id')),
            ],
        ),
    ]
