# Generated by Django 3.2.7 on 2021-09-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0005_auto_20210920_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='customers_access',
            new_name='accounts_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='deliveries_access',
            new_name='action_plan_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='kitchen_stock_access',
            new_name='attendance_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='menu_access',
            new_name='budget_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='orders_access',
            new_name='committees_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='payments_access',
            new_name='dues_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='reservations_access',
            new_name='executives_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='roster_access',
            new_name='groups_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='sittings_access',
            new_name='meetings_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='staff_access',
            new_name='members_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='tables_access',
            new_name='year_access',
        ),
    ]
