# Generated by Django 3.2.7 on 2021-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rink',
            name='rink_source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
