# Generated by Django 3.2.7 on 2021-09-15 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_portal', '0002_alter_rink_rink_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rink',
            name='comment',
            field=models.TextField(null='True'),
        ),
        migrations.AlterField(
            model_name='rink',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_recipient', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AlterField(
            model_name='rink',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_sender', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
