# Generated by Django 3.2.7 on 2022-01-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_portal', '0003_auto_20210915_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rink',
            name='comment',
            field=models.TextField(blank=True, null='True'),
        ),
    ]
