# Generated by Django 3.2.7 on 2021-10-06 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_profile_account'),
        ('module_staff', '0002_auto_20211004_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=100)),
                ('batch_symbol', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('roster_code', models.CharField(blank=True, max_length=20)),
                ('roster_name', models.CharField(blank=True, max_length=100)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RosterDay',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffPersonnel',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='module_roster.batch', to_field='id')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster', to_field='id')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='module_staff.staff', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shift_name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RosterSheet',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='module_roster.batch')),
                ('roster_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module_roster.rosterday', to_field='id')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='module_roster.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_roster.roster', to_field='id'),
        ),
    ]
