# Generated by Django 3.2.7 on 2021-09-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end_date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='start_date',
            new_name='date_start',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
