# Generated by Django 3.2.7 on 2021-10-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_calendar', '0003_auto_20211003_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
