# Generated by Django 3.2.7 on 2021-09-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0005_auto_20210920_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='customers_access',
            new_name='accounts_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='deliveries_access',
            new_name='appraisal_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='kitchen_stock_access',
            new_name='assets_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='menu_access',
            new_name='attendance_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='orders_access',
            new_name='budget_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='payments_access',
            new_name='employees_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='reservations_access',
            new_name='files_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='roster_access',
            new_name='leave_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='sittings_access',
            new_name='ledger_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='staff_access',
            new_name='letters_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='tables_access',
            new_name='payroll_access',
        ),
        migrations.AddField(
            model_name='access',
            name='procurement_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='reception_access',
            field=models.BooleanField(default=False),
        ),
    ]
