# Generated by Django 3.2.7 on 2021-09-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='personal_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='personal_name',
        ),
    ]
