# Generated by Django 3.2.7 on 2021-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_admin', '0005_auto_20210920_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='customers_access',
            new_name='assessment_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='deliveries_access',
            new_name='attendance_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='kitchen_stock_access',
            new_name='classes_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='menu_access',
            new_name='fees_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='orders_access',
            new_name='parents_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='reservations_access',
            new_name='reports_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='roster_access',
            new_name='sections_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='sittings_access',
            new_name='students_access',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='tables_access',
            new_name='subjects_access',
        ),
        migrations.AddField(
            model_name='access',
            name='teachers_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='timetable_access',
            field=models.BooleanField(default=False),
        ),
    ]
