# Generated by Django 3.2.7 on 2021-09-16 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_settings', '0003_auto_20210916_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedprofile',
            name='id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
