# Generated by Django 3.2.7 on 2021-10-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_account'),
        ('module_settings', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='account',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', to_field='id'),
        ),
    ]
