# Generated by Django 3.2.7 on 2022-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_settings', '0003_auto_20211012_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
