# Generated by Django 3.2.7 on 2021-09-20 00:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_profile_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rink',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rink_date', models.DateTimeField(auto_now_add=True)),
                ('rink_type', models.CharField(max_length=50, null=True)),
                ('rink_source', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(null='True')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_recipient', to='accounts.account', to_field='id')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_sender', to='accounts.account', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
